<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bbbe1c28-0c4d-4787-a502-3cc0031cbaee</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quami.Application\Quami.Application.csproj" />
    <ProjectReference Include="..\Quami.Infrastructure\Quami.Infrastructure.csproj" />
  </ItemGroup>

</Project>
