<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Quami.Application\Quami.Application.csproj" />
    <ProjectReference Include="..\Quami.Infrastructure\Quami.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>5719c48c-2dfe-4764-bf5d-c1f706592795</UserSecretsId>
  </PropertyGroup>

</Project>
